name: portfolio
description: portfolio.
version: 1.2.0-dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  url_launcher_web: ^2.0.9
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  network_image_mock: ^2.1.0
  grinder: ^0.9.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
