name: portfolio
description: portfolio.
version: 1.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  url_launcher_web: ^2.0.9
  google_fonts: ^2.3.1
  responsive_builder: ^0.4.2
  auto_route: ^3.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  network_image_mock: ^2.1.0
  grinder: ^0.9.1
  build_runner:

flutter:
  uses-material-design: true
